version: "3.9"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "/myapp/bin/rails server -p 3000 -b 0.0.0.0"
    volumes:
      - ./src:/myapp
    ports:
      - "3000:3000"
    # depends_on:
    #   - db